# Generated by Django 4.0.4 on 2022-06-28 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_department_college_adpd_email_adpd_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UPM', '0003_remove_room_schedule_schedule_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, null=True)),
                ('activity', models.CharField(max_length=300, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('date_approved', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('isRecurring', models.BooleanField(default=False)),
                ('numofstudents', models.IntegerField(null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.adpd')),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.room')),
            ],
        ),
    ]
