# Generated by Django 4.0.4 on 2022-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_remove_booking_date_remove_booking_isrecurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dept_or_office',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
