# Generated by Django 4.0.4 on 2022-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_alter_booking_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='isApproved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
