# Generated by Django 4.0.4 on 2022-08-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0009_alter_booking_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='equipments',
            new_name='equipment',
        ),
    ]
