# Generated by Django 4.0.4 on 2022-12-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0025_remove_room_equipment_room_equipment'),
        ('bookingapp', '0011_booking_isedited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(to='UPM.equipment'),
        ),
    ]
