# Generated by Django 4.0.4 on 2022-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0025_remove_room_equipment_room_equipment'),
        ('bookingapp', '0012_remove_booking_equipment_booking_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(related_name='set', to='UPM.room'),
        ),
    ]
