# Generated by Django 4.0.4 on 2022-12-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_picked',
            field=models.DateField(null=True),
        ),
    ]
