# Generated by Django 4.0.4 on 2022-12-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0017_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
