# Generated by Django 4.0.4 on 2022-12-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0025_remove_room_equipment_room_equipment'),
        ('bookingapp', '0018_remove_booking_equipment_booking_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(to='UPM.equipment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
