# Generated by Django 4.0.4 on 2023-01-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0020_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_picked',
        ),
    ]
