# Generated by Django 4.0.4 on 2022-06-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adpd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='role',
        ),
        migrations.AddField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'faculty'), (2, 'staff'), (3, 'ocs'), (4, 'adpd')], null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
