# Generated by Django 4.0.4 on 2022-06-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_authuser_role_authuser_user_type_delete_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adpd',
            options={'verbose_name_plural': 'ADPDs'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='ocs',
            options={'verbose_name_plural': 'College Secretaries'},
        ),
    ]
