# Generated by Django 4.0.4 on 2022-08-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_adpd_email_remove_adpd_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Faculty'), (2, 'Staff'), (3, 'OCS'), (4, 'ADPD'), (5, 'AO')], null=True),
        ),
    ]
