# Generated by Django 4.0.4 on 2022-08-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0015_term_semester'),
        ('accounts', '0004_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpd',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.college'),
        ),
        migrations.AlterField(
            model_name='ao',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.college'),
        ),
    ]
