# Generated by Django 4.0.4 on 2022-06-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0002_building_term_schedule_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.room'),
        ),
    ]
