# Generated by Django 4.0.4 on 2022-07-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0004_building_slugs_college_slugs_department_slugs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='slugs',
            new_name='slug',
        ),
    ]
