# Generated by Django 4.0.4 on 2022-07-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0006_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='isActivated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
