# Generated by Django 4.0.4 on 2022-07-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0007_term_isactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='room_term', to='UPM.room'),
        ),
    ]
