# Generated by Django 4.0.4 on 2022-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0008_alter_term_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Room'), (2, 'Theatre')], null=True),
        ),
    ]
