# Generated by Django 4.0.4 on 2022-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0009_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='component',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='coursetitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dayofweek',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
