# Generated by Django 4.0.4 on 2022-07-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0010_schedule_capacity_schedule_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='isAvailable',
        ),
        migrations.AddField(
            model_name='schedule',
            name='classnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='term',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.term'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
