# Generated by Django 4.0.4 on 2022-07-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0011_remove_room_isavailable_schedule_classnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.term'),
        ),
    ]
