# Generated by Django 4.0.4 on 2022-07-26 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_adpd_email_remove_adpd_first_name_and_more'),
        ('UPM', '0012_alter_schedule_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='term',
        ),
        migrations.CreateModel(
            name='ScheduleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='schedules/')),
                ('college', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.college')),
                ('ocs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ocs')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.term')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.schedulefile'),
        ),
    ]
