# Generated by Django 4.0.4 on 2022-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0013_remove_schedule_term_schedulefile_schedule_schedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
