# Generated by Django 4.0.4 on 2022-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0014_alter_schedulefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='semester',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
