# Generated by Django 4.0.4 on 2022-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0015_term_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], null=True),
        ),
    ]
