# Generated by Django 4.0.4 on 2022-08-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0016_alter_term_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='semester',
            field=models.CharField(choices=[('1st SEMESTER', '1st Semester'), ('2nd SEMESTER', '2nd Semester')], max_length=50, null=True),
        ),
    ]
