# Generated by Django 4.0.4 on 2022-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0017_alter_term_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classnum',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
