# Generated by Django 4.0.4 on 2022-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0018_alter_schedule_classnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Room'), (2, 'Theatre')], null=True),
        ),
    ]
