# Generated by Django 4.0.4 on 2022-09-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0020_roomtype_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.college'),
        ),
    ]
