# Generated by Django 4.0.4 on 2022-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0021_alter_schedulefile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
