# Generated by Django 4.0.4 on 2022-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0022_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
