# Generated by Django 4.0.4 on 2022-12-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0024_equipment_room_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(to='UPM.equipment'),
        ),
    ]
