# Generated by Django 4.0.4 on 2023-01-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0025_remove_room_equipment_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='semester',
            field=models.CharField(choices=[('1st SEMESTER', '1st Semester'), ('2nd SEMESTER', '2nd Semester'), ('MIDYEAR', 'midyear')], max_length=50, null=True),
        ),
    ]
