# Generated by Django 4.0.4 on 2023-01-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0026_alter_term_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, null=True)),
                ('mobile_number', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
